=== urospetrovic34/camoranesi/autooglas.dtd
<!ELEMENT Autooglas (Automobil)+>
<!ELEMENT Automobil (Proizvodjac,Model,Godiste,Farba,ZapreminaMotora,Transmisija,Gorivo,Cena,KontaktProdavca)>
<!ELEMENT Proizvodjac (#PCDATA)>
<!ELEMENT Model (#PCDATA)>
<!ATTLIST Model tip CDATA #IMPLIED>
<!ELEMENT Godiste (#PCDATA)>
<!ELEMENT Farba (#PCDATA)>
<!ATTLIST Farba tipBoje (Akril|Metalik) #REQUIRED>
<!ELEMENT ZapreminaMotora (#PCDATA)>
<!ATTLIST ZapreminaMotora mernaJedinica (CCM|L) #REQUIRED>
<!ELEMENT Transmisija (#PCDATA)>
<!ATTLIST Transmisija tipPrenosa (Manuelni|Automatik) #REQUIRED>
<!ELEMENT Gorivo (#PCDATA)>
<!ATTLIST Gorivo tng (Da|Ne) #IMPLIED>
<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena valuta (DIN|EUR) #REQUIRED>
<!ELEMENT KontaktProdavca (#PCDATA)>

=== urospetrovic34/camoranesi/autooglas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Autooglas SYSTEM "autooglas.dtd">
<Autooglas>
	<Automobil>
		<Proizvodjac>BMW</Proizvodjac>
		<Model tip="Karavan">530</Model>
		<Godiste>2013</Godiste>
		<Farba tipBoje="Metalik">Crvena</Farba>
		<ZapreminaMotora mernaJedinica="L">500</ZapreminaMotora>
		<Transmisija tipPrenosa="Manuelni">6</Transmisija>
		<Gorivo tng="Ne">700</Gorivo>
		<Cena valuta="EUR">9500</Cena>
		<KontaktProdavca></KontaktProdavca>
	</Automobil>
	<Automobil>
		<Proizvodjac>BMW</Proizvodjac>
		<Model tip="Karavan">530</Model>
		<Godiste>2013</Godiste>
		<Farba tipBoje="Metalik">Crvena</Farba>
		<ZapreminaMotora mernaJedinica="L">500</ZapreminaMotora>
		<Transmisija tipPrenosa="Manuelni">6</Transmisija>
		<Gorivo tng="Ne">700</Gorivo>
		<Cena valuta="EUR">9500</Cena>
		<KontaktProdavca></KontaktProdavca>
	</Automobil>
</Autooglas>
