=== urospetrovic34/camoranesi/zad6.dtd
<!ELEMENT Fakultet (Student)+>
<!ELEMENT Student (Osoba,Upisi+)>
<!ATTLIST Student status (studira|diplomirao) #REQUIRED>
<!ATTLIST Student indeks ID #REQUIRED>
<!ELEMENT Osoba (Ime,Prezime,MestoRodjenja,DatumRodjenja)>
<!ELEMENT Ime (#PCDATA)>
<!ELEMENT Prezime (#PCDATA)>
<!ELEMENT MestoRodjenja (#PCDATA)>
<!ELEMENT DatumRodjenja (#PCDATA)>
<!ELEMENT Upisi (Semestar+)>
<!ELEMENT Semestar (#PCDATA)>
<!ATTLIST Semestar broj CDATA #REQUIRED>
<!ATTLIST Semestar godina CDATA #REQUIRED>
<!ATTLIST Semestar vrsta (budzet|saf) #REQUIRED>

=== urospetrovic34/camoranesi/zad6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Fakultet SYSTEM "zad6.dtd">
<Fakultet>
	<Student status="studira" indeks="nrt_105_17">
		<Osoba>
			<Ime>Uros</Ime>
			<Prezime>Petrovic</Prezime>
			<MestoRodjenja>Beograd</MestoRodjenja>
			<DatumRodjenja>03.08.1998</DatumRodjenja>
		</Osoba>
		<Upisi>
			<Semestar broj="1" godina="1" vrsta="saf">
			</Semestar>
			<Semestar broj="2" godina="1" vrsta="saf">
			</Semestar>
			<Semestar broj="3" godina="2" vrsta="budzet">
			</Semestar>
			<Semestar broj="4" godina="2" vrsta="budzet">
			</Semestar>
			<Semestar broj="5" godina="3" vrsta="budzet">
			</Semestar>
			<Semestar broj="6" godina="3" vrsta="budzet">
			</Semestar>
		</Upisi>
	</Student>
	<Student status="diplomirao" indeks="rt_217_18">
		<Osoba>
			<Ime>Osoba</Ime>
			<Prezime>B</Prezime>
			<MestoRodjenja>Beograd</MestoRodjenja>
			<DatumRodjenja>01.01.1993</DatumRodjenja>
		</Osoba>
		<Upisi>
			<Semestar broj="1" godina="1" vrsta="budzet">
			</Semestar>
			<Semestar broj="2" godina="1" vrsta="budzet">
			</Semestar>
			<Semestar broj="3" godina="2" vrsta="budzet">
			</Semestar>
			<Semestar broj="4" godina="2" vrsta="budzet">
			</Semestar>
		</Upisi>
	</Student>
</Fakultet>
